services:
  db:
    image: postgres:16-alpine
    container_name: ufac_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: khushi
      POSTGRES_PASSWORD: soha
      POSTGRES_DB: ufac
    ports:
      - '5437:5432'
    volumes:
      - ufac_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U khushi -d ufac']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ufac_pgdata:
